USE challenge;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  created_date DATETIME DEFAULT NOW()
);

CREATE TABLE Messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(500) NOT NULL,
  created_date DATETIME DEFAULT NOW(),
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
