USE challenge;

CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  created_date DATE DEFAULT GETDATE()
);

CREATE TABLE Messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(500) NOT NULL,
  created_date DATE DEFAULT GETDATE(),
  user_id INT NOT NULL FOREIGN KEY REFERENCES Users(id)
);
